# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Comms_pb2 as Comms__pb2


class ListeningCommsStub(object):
  """*
  This will be a work in progress for all of the 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TimeData = channel.unary_unary(
        '/ListeningComms/TimeData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.TimeResponse.FromString,
        )
    self.DateData = channel.unary_unary(
        '/ListeningComms/DateData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.DateResponse.FromString,
        )
    self.EmailData = channel.unary_unary(
        '/ListeningComms/EmailData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.EmailResponse.FromString,
        )
    self.CalendarData = channel.unary_unary(
        '/ListeningComms/CalendarData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.CalendarResponse.FromString,
        )
    self.WeatherData = channel.unary_unary(
        '/ListeningComms/WeatherData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.WeatherResponse.FromString,
        )
    self.NewsData = channel.unary_unary(
        '/ListeningComms/NewsData',
        request_serializer=Comms__pb2.GenericRequest.SerializeToString,
        response_deserializer=Comms__pb2.NewsResponse.FromString,
        )


class ListeningCommsServicer(object):
  """*
  This will be a work in progress for all of the 
  """

  def TimeData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DateData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EmailData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CalendarData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WeatherData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewsData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ListeningCommsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TimeData': grpc.unary_unary_rpc_method_handler(
          servicer.TimeData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.TimeResponse.SerializeToString,
      ),
      'DateData': grpc.unary_unary_rpc_method_handler(
          servicer.DateData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.DateResponse.SerializeToString,
      ),
      'EmailData': grpc.unary_unary_rpc_method_handler(
          servicer.EmailData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.EmailResponse.SerializeToString,
      ),
      'CalendarData': grpc.unary_unary_rpc_method_handler(
          servicer.CalendarData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.CalendarResponse.SerializeToString,
      ),
      'WeatherData': grpc.unary_unary_rpc_method_handler(
          servicer.WeatherData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.WeatherResponse.SerializeToString,
      ),
      'NewsData': grpc.unary_unary_rpc_method_handler(
          servicer.NewsData,
          request_deserializer=Comms__pb2.GenericRequest.FromString,
          response_serializer=Comms__pb2.NewsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ListeningComms', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
