# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testprotofile_pb2 as testprotofile__pb2


class testServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.testSend = channel.unary_unary(
        '/testService/testSend',
        request_serializer=testprotofile__pb2.testRequest.SerializeToString,
        response_deserializer=testprotofile__pb2.testResponse.FromString,
        )


class testServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def testSend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_testServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'testSend': grpc.unary_unary_rpc_method_handler(
          servicer.testSend,
          request_deserializer=testprotofile__pb2.testRequest.FromString,
          response_serializer=testprotofile__pb2.testResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'testService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
