# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import attempt1_pb2 as attempt1__pb2


class testSendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sampleData = channel.unary_unary(
        '/testSend/sampleData',
        request_serializer=attempt1__pb2.Request.SerializeToString,
        response_deserializer=attempt1__pb2.Response.FromString,
        )


class testSendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sampleData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_testSendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sampleData': grpc.unary_unary_rpc_method_handler(
          servicer.sampleData,
          request_deserializer=attempt1__pb2.Request.FromString,
          response_serializer=attempt1__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'testSend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
